#!/bin/bash

mkdir array_list
cd array_list
touch mod.rs
cd /home/dom/development/learning/algorithms/dna/src
mkdir bfs_graph_matrix
cd bfs_graph_matrix
touch mod.rs
cd /home/dom/development/learning/algorithms/dna/src
mkdir binary_search_list
cd binary_search_list
touch mod.rs
cd /home/dom/development/learning/algorithms/dna/src
mkdir btbfs
cd btbfs
touch mod.rs
cd /home/dom/development/learning/algorithms/dna/src
mkdir bt_in_order
cd bt_in_order
touch mod.rs
cd /home/dom/development/learning/algorithms/dna/src
mkdir bt_post_order
cd bt_post_order
touch mod.rs
cd /home/dom/development/learning/algorithms/dna/src
mkdir bt_pre_order
cd bt_pre_order
touch mod.rs
cd /home/dom/development/learning/algorithms/dna/src
mkdir bubble_sort
cd bubble_sort
touch mod.rs
cd /home/dom/development/learning/algorithms/dna/src
mkdir compare_binary_trees
cd compare_binary_trees
touch mod.rs
cd /home/dom/development/learning/algorithms/dna/src
mkdir dfs_graph_list
cd dfs_graph_list
touch mod.rs
cd /home/dom/development/learning/algorithms/dna/src
mkdir dfs_on_bst
cd dfs_on_bst
touch mod.rs
cd /home/dom/development/learning/algorithms/dna/src
mkdir doubly_linked_list
cd doubly_linked_list
touch mod.rs
cd /home/dom/development/learning/algorithms/dna/src
mkdir linear_search_list
cd linear_search_list
touch mod.rs
cd /home/dom/development/learning/algorithms/dna/src
mkdir lru
cd lru
touch mod.rs
cd /home/dom/development/learning/algorithms/dna/src
mkdir map
cd map
touch mod.rs
cd /home/dom/development/learning/algorithms/dna/src
mkdir maze_solver
cd maze_solver
touch mod.rs
cd /home/dom/development/learning/algorithms/dna/src
mkdir min_heap
cd min_heap
touch mod.rs
cd /home/dom/development/learning/algorithms/dna/src
mkdir queue
cd queue
touch mod.rs
cd /home/dom/development/learning/algorithms/dna/src
mkdir quick_sort
cd quick_sort
touch mod.rs
cd /home/dom/development/learning/algorithms/dna/src
mkdir singly_linked_list
cd singly_linked_list
touch mod.rs
cd /home/dom/development/learning/algorithms/dna/src
mkdir stack
cd stack
touch mod.rs
cd /home/dom/development/learning/algorithms/dna/src
mkdir trie
cd trie
touch mod.rs
cd /home/dom/development/learning/algorithms/dna/src
mkdir two_crystal_balls
cd two_crystal_balls
touch mod.rs
cd /home/dom/development/learning/algorithms/dna/src
